### PR TITLE
#54 - Added Upload abstraction and Repo.upload() method

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #54 
Added blob upload abstraction & AstoUpload placeholder

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#87](https://github.com/artipie/docker-adapter/issues/87) is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c2c29cab-7a40-46df-bf7e-5f3a522bfd47); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by olegmoz** [comment]
@HDouss added basic test, disabled for now

**Comment by HDouss** [comment]
@olegmoz The idea is to make a puzzle to implement AstoUpload methods and to reenable the test, otherwise, we could forget about that.

**Comment by olegmoz** [comment]
@HDouss added puzzle for AstoUpload implementation

**Comment by olegmoz** [comment]
@g4s8 build check crashes due to exception in CodeCov plugin, some host is not responding. Could you please restart it?

**Comment by HDouss** [comment]
@g4s8 Please merge.

**Comment by HDouss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/docker-adapter/issues/87#issuecomment-618594247))

@HDouss This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#87](https://github.com/artipie/docker-adapter/issues/87) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `REV`
  * The job is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @hdouss[/z](https://www.0crat.com/u/hdouss) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @olegmoz[/z](https://www.0crat.com/u/olegmoz): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fdocker-adapter%2387%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by HDouss** [comment]
@g4s8 how to trigger rewards here?

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/docker-adapter/issues/87#issuecomment-618858173))

@g4s8 Job [#87](https://github.com/artipie/docker-adapter/issues/87) is not in the agenda of @hdouss[/z](https://www.0crat.com/u/hdouss), can't set title

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/docker-adapter/issues/87#issuecomment-618858173))

@g4s8 Job [#87](https://github.com/artipie/docker-adapter/issues/87) is not in the agenda of @hdouss[/z](https://www.0crat.com/u/hdouss), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@HDouss please make sure you will find at least 3 issues during next CR, thanks

**Comment by HDouss** [comment]
@sereshqua Sure. Sometimes it is really hard to find 3 comments to do.

**Comment by sereshqua** [comment]
> @sereshqua Sure. Sometimes it is really hard to find 3 comments to do.

@HDouss totally understand you, but it is all about policy :)

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
