### PR TITLE
#422 - Handling empty UUID

### LINKED ISSUE #422: Empty upload UUIDs should be prohibited
Now it is possible to specify empty UUID in request, but it should be prohibited. An error should be returned in this case

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #422 
Handling empty UUID

### CODE REVIEW

**Review by olenagerasimova — DISMISSED** [review]
@olegmoz thanks, looks good to merge

**Comment by olenagerasimova** [comment]
@olegmoz but please, fix check style

**Comment by olegmoz** [comment]
@olenagerasimova thanks, fixed the issue. Please approve

**Review by olenagerasimova — APPROVED** [review]
@olegmoz approving

**Pull request merged**
