### PR TITLE
#54 - Updated example repo with one with valid binary content

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #54 
Repository example in resources was broken: digests mismatched actual content in blobs. Created new example repository with single image to use later in integration tests

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#67](https://github.com/artipie/docker-adapter/issues/67) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d5887888-5a16-43dc-a307-a185d19dbf7c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by olegmoz** [comment]
@Vatavuk ping

**Comment by Vatavuk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/docker-adapter/issues/67#issuecomment-609680724))

@Vatavuk This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#67](https://github.com/artipie/docker-adapter/issues/67) is [in scope](http://www.zerocracy.com/policy.html#14) for 4days
  * The role is `REV`
  * The job is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @olegmoz[/z](https://www.0crat.com/u/olegmoz): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fdocker-adapter%2367%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job [#67](https://github.com/artipie/docker-adapter/issues/67) is not in the agenda of @vatavuk[/z](https://www.0crat.com/u/vatavuk), can't set title

**Comment by 0crat** [comment]
Job [#67](https://github.com/artipie/docker-adapter/issues/67) is not in the agenda of @vatavuk[/z](https://www.0crat.com/u/vatavuk), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
