### PR TITLE
#54 - AstoRepo refactored to access blobs via BlobStore

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #54
Refactored AstoRepo to access blobs via BlobStore, not by direct access to Storage instance.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#112](https://github.com/artipie/docker-adapter/issues/112) is assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a98aa3f3-5938-4464-9170-0b1fbdbb6984); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ae73ab37-41ee-4e38-af1d-a3b0f49d9fc0, thread: PQ-CT2E6TK9B
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1359] com.amazonaws.ResetException: Failed to reset the request input stream;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)
java.io.BufferedInputStream[170] java.io.IOException: Stream closed
```

[0.53.14](https://github.com/zerocracy/farm): CID: [5c8dfd85-97bf-41f8-891b-c168a6cda7fb](https://www.0crat.com/footprint/CT2E6TK9B/5c8dfd85-97bf-41f8-891b-c168a6cda7fb), Type: "Order was given"

**Comment by 0crat** [comment]
Job [#112](https://github.com/artipie/docker-adapter/issues/112) is not in the agenda of @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), can't set title

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#112](https://github.com/artipie/docker-adapter/issues/112) is not in the agenda of @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
