### PR TITLE
#73 - Improvements to storage structure description in SPEC.md

### LINKED ISSUE #73: Unclear phrases in spec
These two sentences in spec.md looks unclear:

> Uploads of layers are managed in the uploads directory, which is key by upload id.

> While the registry can save all revisions of a manifest, no relationship is
implied as to the ordering of changes to a manifest.

May it's possible to improve them somehow?

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #73

### CODE REVIEW

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by olegmoz** [comment]
@g4s8 please take a look at this PR, since it is small and no reviewer assigned

**Comment by olegmoz** [comment]
@olenagerasimova ping

**Comment by olegmoz** [comment]
@olenagerasimova thank you!
@g4s8 cannot merge the PR, maybe due to one failing check or missing formal review. Could you please see into this and maybe update my permissions in the project?

**Comment by g4s8** [comment]
@olegmoz please try again, should be fixed by https://github.com/artipie/docker-adapter/commit/eade97639f7d00439c7463e9fb6f80a553ee2f27

**Comment by olegmoz** [comment]
@g4s8 thank you, merged this PR

**Pull request merged**
