### PR TITLE
Save blob to storage

### PR DESCRIPTION
**Pull request by g4s8**
#41 - save `tmp` blob to storage and delete `tmp` file after complete in `AstoBlob#put`. Added `RepoRoot` base key and reuse it in `AstoRepo` class.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#42](https://github.com/artipie/docker-adapter/issues/42) is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/4ae845c3-148a-4d86-a216-64a2fab8d428); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
> @g4s8 overall, it looks good, but I have only one suggestion: maybe we should leave a puzzle to decompose `AstoBlobs#put` to make it less difficult to understand (this method has become really bulky). What do you think?

@iakunin I agree, added a puzzle about it: https://github.com/artipie/docker-adapter/pull/42/commits/b618fd9794f6371f78b36e171a6a5ad7ebbaf640

**Comment by 0crat** [comment]
Job audit: performer @iakunin[/z](https://www.0crat.com/u/iakunin)[/z](https://www.0crat.com/u/iakunin) didn't make CR comments

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Pull request merged**
